### ISSUE TITLE
RSS Feed with null published date is assigned DateTime.Now()

### ISSUE THREAD

**Issue by PromoFaux** [codekoenig/SyndicationToolbox#1]
Hello! I'm using your library over on [MattermostRSS](https://github.com/promofaux/mattermostrss), and I've run into a bit of an issue...

Currently, I rely on the `PublishDate` field to work out whether or not I have already processed an item in the feed. To do this, I order feed by `PublishDate`, and store the value of the latest processed item, and then on the next grab, only look for feed items with a greater value in `PublishDate`.

This is causing issues when feeds don't include the published date. Ideally I would just ignore those.

Looking at a similar [library](https://github.com/codehollow/FeedReader), I notice that they leave the publish date as null. Is there a reason you set it to the current date and time?

If I'm using it wrong, then I guess I can use FeedReader instead, but thought I would ask you first!

Cheers

https://github.com/codekoenig/SyndicationToolbox/blob/2addb7ccc8a26e74265e0c1e2180b9e0a9e8a0f9/SyndicationToolbox/RSSFeedParser.cs#L46

**Comment by codekoenig** [comment]
The reason is that this library was built for my own feed aggregator which permanently crawled all subscribed feeds and thus, if no publish date was given, would come pretty close to the actual publish date by simply using the current date.

But, of course, this is something that should be in the domain of the aggregator and not in the domain of the parser and I let aggregator logic leak into the parser library, so this is obviously a misbehavior. I can see you already have switched the library as I was late to respond, but still many thanks for pointing it out, I will fix this and update the NuGet package.
